/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalprojectgradebook;
import java.io.File;
import java.io.IOException;
import java.io.FileWriter; 
import java.io.BufferedWriter;

/**
 *
 * @author edith
 */
public class TCreateClass extends javax.swing.JFrame {

    /**
     * Creates new form TCreateClass
     */
    public TCreateClass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        TeacherID2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TCCIG1 = new javax.swing.JSpinner();
        TCCIG2 = new javax.swing.JSpinner();
        TCCIG3 = new javax.swing.JSpinner();
        TCCIG4 = new javax.swing.JSpinner();
        TCCIG5 = new javax.swing.JSpinner();
        TCCLast1 = new javax.swing.JTextField();
        TCCLast2 = new javax.swing.JTextField();
        TCCLast3 = new javax.swing.JTextField();
        TCCLast4 = new javax.swing.JTextField();
        TCCLast5 = new javax.swing.JTextField();
        TCCID1 = new javax.swing.JTextField();
        TCCID2 = new javax.swing.JTextField();
        TCCID3 = new javax.swing.JTextField();
        TCCID4 = new javax.swing.JTextField();
        TCCID5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        TeacherID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ClassID = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        TeacherID2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Teacher ID:");

        jLabel2.setText(" Last Name");

        jLabel3.setText("Student ID");

        jLabel4.setText("Initial Grade");

        TCCLast1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCCLast1ActionPerformed(evt);
            }
        });

        TCCID4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCCID4ActionPerformed(evt);
            }
        });

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Class ID:");

        ClassID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TCCLast1)
                                        .addComponent(TCCLast2)
                                        .addComponent(TCCLast3)
                                        .addComponent(TCCLast4)
                                        .addComponent(TCCLast5, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TeacherID, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(TCCID1)
                            .addComponent(TCCID2)
                            .addComponent(TCCID3)
                            .addComponent(TCCID4)
                            .addComponent(TCCID5, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jButton1)
                            .addComponent(TCCIG1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(TCCIG2)
                            .addComponent(TCCIG3)
                            .addComponent(TCCIG4)
                            .addComponent(TCCIG5))
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClassID)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TeacherID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(ClassID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCCIG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCCLast1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCCID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCCIG2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCCLast2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCCID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCCIG3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCCLast3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCCID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCCIG4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCCLast4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCCID4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCCIG5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCCLast5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCCID5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String Header = "Student ID   Class ID   Teacher ID   LastName   Grade" + "\n";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Teacher1 obj = new  Teacher1();
        obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TCCLast1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCCLast1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCCLast1ActionPerformed

    private void TCCID4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCCID4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TCCID4ActionPerformed

    char LetterGrade(int x){
    if (x >= 9){
      return 'A';
    }
    else if (x >= 8){
      return 'B';
    }
    else if (x >= 7){
      return 'C';
    }
    else if (x >= 6){
      return 'D';
    }
    else {
      return 'F';
    }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
    String TCCStudent1 = "  S-"+TCCID1.getText()+ "       " + "Z-"+ ClassID.getText() + "     "+ "T-"+ TeacherID.getText() +"     "+ TCCLast1.getText()+ "    "+ LetterGrade((int)TCCIG1.getValue())+"\n";
    String TCCStudent2 = "  S-"+TCCID2.getText()+ "       " + "Z-"+ClassID.getText() + "      "+ "T-"+ TeacherID.getText() +"     "+ TCCLast2.getText()+ "    "+ LetterGrade((int)TCCIG2.getValue())+"\n";
    String TCCStudent3 = "  S-"+TCCID3.getText()+ "       " + "Z-"+ClassID.getText() + "      "+ "T-"+ TeacherID.getText() +"     "+ TCCLast3.getText()+ "    "+ LetterGrade((int)TCCIG3.getValue())+"\n";
    String TCCStudent4 = "  S-"+TCCID4.getText()+ "       " + "Z-"+ClassID.getText() + "      "+ "T-"+ TeacherID.getText() +"     "+ TCCLast4.getText()+ "    "+ LetterGrade((int)TCCIG4.getValue())+"\n";
    String TCCStudent5 = "  S-"+TCCID5.getText()+ "       " + "Z-"+ClassID.getText() + "      "+ "T-"+ TeacherID.getText() +"     "+ TCCLast5.getText()+ "    "+ LetterGrade((int)TCCIG5.getValue())+"\n";
    String ClassFile = "Z-"+ClassID.getText() + ".txt";
    String TeacherFile = "T-"+TeacherID.getText()+ ".txt";
    String Student1File = "S-"+TCCID1.getText()+ ".txt";
    String Student2File = "S-"+TCCID2.getText()+ ".txt";
    String Student3File = "S-"+TCCID3.getText()+ ".txt";
    String Student4File = "S-"+TCCID4.getText()+ ".txt";
    String Student5File = "S-"+TCCID5.getText()+ ".txt";
    

    try {
      File myObj = new File(ClassFile);
      if (myObj.createNewFile()) {
        System.out.println("File created: " + myObj.getName());
      } else {
        System.out.println("File already exists.");
      }
    } catch (IOException e) {
      System.out.println("An error occurred.");
      e.printStackTrace();
    }
    try {
      BufferedWriter myWriter = new BufferedWriter((new FileWriter(ClassFile, true)));
      myWriter.write(Header);
      myWriter.write(TCCStudent1);
      myWriter.write(TCCStudent2);
      myWriter.write(TCCStudent3);
      myWriter.write(TCCStudent4);
      myWriter.write(TCCStudent5);
      myWriter.close();
      System.out.println("Successfully wrote to the file.");
    } catch (IOException e) {
      System.out.println("An error occurred in processing .");
      e.printStackTrace();
    }
    try {
      File myObj = new File(TeacherFile);
      if (myObj.createNewFile()) {
        System.out.println("File created: " + myObj.getName());
      } else {
        System.out.println("File already exists.");
      }
    } catch (IOException e) {
      System.out.println("An error occurred.");
      e.printStackTrace();
    }
    try {
      BufferedWriter myWriter = new BufferedWriter(new FileWriter(TeacherFile, true));
      myWriter.write(Header);
      myWriter.write(TCCStudent1);
      myWriter.write(TCCStudent2);
      myWriter.write(TCCStudent3);
      myWriter.write(TCCStudent4);
      myWriter.write(TCCStudent5);
      myWriter.close();
      System.out.println("Successfully wrote to the file.");
    } catch (IOException e) {
      System.out.println("An error occurred in processing .");
      e.printStackTrace();
    }
    try {
      File myObj = new File(Student1File);
      if (myObj.createNewFile()) {
        System.out.println("File created: " + myObj.getName());
      } else {
        System.out.println("File already exists.");
      }
    } catch (IOException e) {
      System.out.println("An error occurred.");
      e.printStackTrace();
    }
    try {
      BufferedWriter myWriter = new BufferedWriter(new FileWriter(Student1File, true));
      myWriter.write(TCCStudent1);

      myWriter.close();
      System.out.println("Successfully wrote to the file.");
    } catch (IOException e) {
      System.out.println("An error occurred in processing .");
      e.printStackTrace();
    }
    try {
      File myObj = new File(Student2File);
      if (myObj.createNewFile()) {
        System.out.println("File created: " + myObj.getName());
      } else {
        System.out.println("File already exists.");
      }
    } catch (IOException e) {
      System.out.println("An error occurred.");
      e.printStackTrace();
    }
    try {
      BufferedWriter myWriter = new BufferedWriter (new FileWriter(Student2File, true));
      myWriter.write(TCCStudent2);

      myWriter.close();
      System.out.println("Successfully wrote to the file.");
    } catch (IOException e) {
      System.out.println("An error occurred in processing .");
      e.printStackTrace();
    }
    try {
      File myObj = new File(Student3File);
      if (myObj.createNewFile()) {
        System.out.println("File created: " + myObj.getName());
      } else {
        System.out.println("File already exists.");
      }
    } catch (IOException e) {
      System.out.println("An error occurred.");
      e.printStackTrace();
    }
    try {
      BufferedWriter myWriter = new BufferedWriter(new FileWriter(Student3File, true));
      myWriter.write(TCCStudent3);

      myWriter.close();
      System.out.println("Successfully wrote to the file.");
    } catch (IOException e) {
      System.out.println("An error occurred in processing .");
      e.printStackTrace();
    }
    try {
      File myObj = new File(Student4File);
      if (myObj.createNewFile()) {
        System.out.println("File created: " + myObj.getName());
      } else {
        System.out.println("File already exists.");
      }
    } catch (IOException e) {
      System.out.println("An error occurred.");
      e.printStackTrace();
    }
    try {
      BufferedWriter myWriter = new BufferedWriter(new FileWriter(Student4File, true));
      myWriter.write(TCCStudent4);

      myWriter.close();
      System.out.println("Successfully wrote to the file.");
    } catch (IOException e) {
      System.out.println("An error occurred in processing .");
      e.printStackTrace();
    }
    try {
      File myObj = new File(Student5File);
      if (myObj.createNewFile()) {
        System.out.println("File created: " + myObj.getName());
      } else {
        System.out.println("File already exists.");
      }
    } catch (IOException e) {
      System.out.println("An error occurred.");
      e.printStackTrace();
    }
    try {
      BufferedWriter myWriter = new BufferedWriter(new FileWriter(Student5File, true));
      myWriter.write(TCCStudent5);
      myWriter.close();
      System.out.println("Successfully wrote to the file.");
    } catch (IOException e) {
      System.out.println("An error occurred in processing .");
      e.printStackTrace();
    }
    
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ClassIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClassIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCreateClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCreateClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCreateClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCreateClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TCreateClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ClassID;
    private javax.swing.JTextField TCCID1;
    private javax.swing.JTextField TCCID2;
    private javax.swing.JTextField TCCID3;
    private javax.swing.JTextField TCCID4;
    private javax.swing.JTextField TCCID5;
    private javax.swing.JSpinner TCCIG1;
    private javax.swing.JSpinner TCCIG2;
    private javax.swing.JSpinner TCCIG3;
    private javax.swing.JSpinner TCCIG4;
    private javax.swing.JSpinner TCCIG5;
    private javax.swing.JTextField TCCLast1;
    private javax.swing.JTextField TCCLast2;
    private javax.swing.JTextField TCCLast3;
    private javax.swing.JTextField TCCLast4;
    private javax.swing.JTextField TCCLast5;
    private javax.swing.JTextField TeacherID;
    private javax.swing.JLabel TeacherID2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
